import { ImgSrc } from './types';

const images: ImgSrc[] = [
  { name: 'people_1', src: require('../assets/people/1.jpg') },
  { name: 'people_2', src: require('../assets/people/2.jpg') },
  { name: 'people_3', src: require('../assets/people/3.jpg') },
  { name: 'people_4', src: require('../assets/people/4.jpg') },
  { name: 'people_5', src: require('../assets/people/5.jpg') },
  { name: 'people_6', src: require('../assets/people/6.jpg') },
  { name: 'people_7', src: require('../assets/people/7.jpg') },
  { name: 'people_8', src: require('../assets/people/8.jpg') },
  { name: 'people_9', src: require('../assets/people/9.jpg') },
  { name: 'people_10', src: require('../assets/people/10.jpg') },
  { name: 'people_11', src: require('../assets/people/11.jpg') },
  { name: 'people_12', src: require('../assets/people/12.jpg') },
  { name: 'people_13', src: require('../assets/people/13.jpg') },
  { name: 'people_14', src: require('../assets/people/14.jpg') },
  { name: 'people_15', src: require('../assets/people/15.jpg') },
  { name: 'people_16', src: require('../assets/people/16.jpg') },
  //   { name: 'people_17', src: require('../assets/people/17.jpg') },
  { name: 'people_18', src: require('../assets/people/18.jpg') },
  { name: 'people_19', src: require('../assets/people/19.jpg') },
  { name: 'people_20', src: require('../assets/people/20.jpg') },
  { name: 'people_21', src: require('../assets/people/21.jpg') },
  { name: 'people_22', src: require('../assets/people/22.jpg') },
  { name: 'people_23', src: require('../assets/people/23.jpg') },
  { name: 'people_24', src: require('../assets/people/24.jpg') },
  { name: 'people_25', src: require('../assets/people/25.jpg') },
  { name: 'people_26', src: require('../assets/people/26.jpg') },
  { name: 'people_27', src: require('../assets/people/27.jpg') },
  { name: 'people_28', src: require('../assets/people/28.jpg') },
  { name: 'people_29', src: require('../assets/people/29.jpg') },
  { name: 'people_30', src: require('../assets/people/30.jpg') },
  { name: 'people_31', src: require('../assets/people/31.jpg') },
  { name: 'people_32', src: require('../assets/people/32.jpg') },
  { name: 'people_33', src: require('../assets/people/33.jpg') },
  { name: 'people_34', src: require('../assets/people/34.jpg') },
  { name: 'people_35', src: require('../assets/people/35.jpg') },
  { name: 'people_36', src: require('../assets/people/36.jpg') },
  { name: 'people_37', src: require('../assets/people/37.jpg') },
  { name: 'people_38', src: require('../assets/people/38.jpg') },
  { name: 'people_39', src: require('../assets/people/39.jpg') },
  { name: 'people_40', src: require('../assets/people/40.jpg') },
  { name: 'people_41', src: require('../assets/people/41.jpg') },
  { name: 'people_42', src: require('../assets/people/42.jpg') },
  { name: 'people_43', src: require('../assets/people/43.jpg') },
  { name: 'people_44', src: require('../assets/people/44.jpg') },
  { name: 'people_45', src: require('../assets/people/45.jpg') },
  { name: 'people_46', src: require('../assets/people/46.jpg') },
  { name: 'people_47', src: require('../assets/people/47.jpg') },
  { name: 'people_48', src: require('../assets/people/48.jpg') },
  { name: 'people_49', src: require('../assets/people/49.jpg') },
  { name: 'people_50', src: require('../assets/people/50.jpg') },
  { name: 'people_51', src: require('../assets/people/51.jpg') },
  { name: 'people_52', src: require('../assets/people/52.jpg') },
  { name: 'people_53', src: require('../assets/people/53.jpg') },
  { name: 'people_54', src: require('../assets/people/54.jpg') },
  { name: 'people_55', src: require('../assets/people/55.jpg') },
  { name: 'people_56', src: require('../assets/people/56.jpg') },
  { name: 'people_57', src: require('../assets/people/57.jpg') },
  { name: 'people_58', src: require('../assets/people/58.jpg') },
  { name: 'people_59', src: require('../assets/people/59.jpg') },
  { name: 'people_60', src: require('../assets/people/60.jpg') },
  { name: 'people_61', src: require('../assets/people/61.jpg') },
  { name: 'people_62', src: require('../assets/people/62.jpg') },
  { name: 'people_63', src: require('../assets/people/63.jpg') },
  { name: 'people_64', src: require('../assets/people/64.jpg') },
  { name: 'people_65', src: require('../assets/people/65.jpg') },
  { name: 'people_66', src: require('../assets/people/66.jpg') },
  { name: 'people_67', src: require('../assets/people/67.jpg') },
  { name: 'people_68', src: require('../assets/people/68.jpg') },
  { name: 'people_69', src: require('../assets/people/69.jpg') },
  { name: 'people_70', src: require('../assets/people/70.jpg') },
  { name: 'people_71', src: require('../assets/people/71.jpg') },
  { name: 'people_72', src: require('../assets/people/72.jpg') },
  { name: 'people_73', src: require('../assets/people/73.jpg') },
  { name: 'people_74', src: require('../assets/people/74.jpg') },
  { name: 'people_75', src: require('../assets/people/75.jpg') },
  { name: 'people_76', src: require('../assets/people/76.jpg') },
  { name: 'people_77', src: require('../assets/people/77.jpg') },
  { name: 'people_78', src: require('../assets/people/78.jpg') },
  { name: 'people_79', src: require('../assets/people/79.jpg') },
  { name: 'people_80', src: require('../assets/people/80.jpg') },
  { name: 'people_81', src: require('../assets/people/81.jpg') },
  { name: 'people_82', src: require('../assets/people/82.jpg') },
  //   { name: 'vehicles_1', src: require('../assets/vehicles/1.jpg') },
  //   { name: 'vehicles_2', src: require('../assets/vehicles/2.jpg') },
  //   { name: 'vehicles_3', src: require('../assets/vehicles/3.jpg') },
  { name: 'vehicles_4', src: require('../assets/vehicles/4.jpg') },
  //   { name: 'vehicles_5', src: require('../assets/vehicles/5.jpg') },
  { name: 'vehicles_6', src: require('../assets/vehicles/6.jpg') },
  { name: 'vehicles_7', src: require('../assets/vehicles/7.jpg') },
  { name: 'vehicles_8', src: require('../assets/vehicles/8.jpg') },
  //   { name: 'vehicles_9', src: require('../assets/vehicles/9.jpg') },
  //   { name: 'vehicles_10', src: require('../assets/vehicles/10.jpg') },
  //   { name: 'vehicles_11', src: require('../assets/vehicles/11.jpg') },
  //   { name: 'vehicles_12', src: require('../assets/vehicles/12.jpg') },
  //   { name: 'vehicles_13', src: require('../assets/vehicles/13.jpg') },
  { name: 'vehicles_14', src: require('../assets/vehicles/14.jpg') },
  //   { name: 'vehicles_15', src: require('../assets/vehicles/15.jpg') },
  { name: 'vehicles_16', src: require('../assets/vehicles/16.jpg') },
  //   { name: 'vehicles_17', src: require('../assets/vehicles/17.jpg') },
  { name: 'vehicles_18', src: require('../assets/vehicles/18.jpg') },
  { name: 'vehicles_19', src: require('../assets/vehicles/19.jpg') },
  { name: 'vehicles_20', src: require('../assets/vehicles/20.jpg') },
  //   { name: 'vehicles_21', src: require('../assets/vehicles/21.jpg') },
  //   { name: 'vehicles_22', src: require('../assets/vehicles/22.jpg') },
  //   { name: 'vehicles_23', src: require('../assets/vehicles/23.jpg') },
  { name: 'vehicles_24', src: require('../assets/vehicles/24.jpg') },
  { name: 'vehicles_25', src: require('../assets/vehicles/25.jpg') },
  { name: 'vehicles_26', src: require('../assets/vehicles/26.jpg') },
  //   { name: 'vehicles_27', src: require('../assets/vehicles/27.jpg') },
  //   { name: 'vehicles_28', src: require('../assets/vehicles/28.jpg') },
  //   { name: 'vehicles_29', src: require('../assets/vehicles/29.jpg') },
  { name: 'vehicles_30', src: require('../assets/vehicles/30.jpg') },
  //   { name: 'vehicles_31', src: require('../assets/vehicles/31.jpg') },
  //   { name: 'vehicles_32', src: require('../assets/vehicles/32.jpg') },
  { name: 'vehicles_33', src: require('../assets/vehicles/33.jpg') },
  { name: 'vehicles_34', src: require('../assets/vehicles/34.jpg') },
  { name: 'vehicles_35', src: require('../assets/vehicles/35.jpg') },
  { name: 'vehicles_36', src: require('../assets/vehicles/36.jpg') },
  { name: 'vehicles_37', src: require('../assets/vehicles/37.jpg') },
  { name: 'vehicles_38', src: require('../assets/vehicles/38.jpg') },
  //   { name: 'vehicles_39', src: require('../assets/vehicles/39.jpg') },
  //   { name: 'starships_1', src: require('../assets/starships/1.jpg') },
  //   { name: 'starships_2', src: require('../assets/starships/2.jpg') }, // CR90 corvette
  //   { name: 'starships_3', src: require('../assets/starships/3.jpg') }, // Star Destroyer
  //   { name: 'starships_4', src: require('../assets/starships/4.jpg') },
  { name: 'starships_5', src: require('../assets/starships/5.jpg') },
  //   { name: 'starships_6', src: require('../assets/starships/6.jpg') },
  //   { name: 'starships_7', src: require('../assets/starships/7.jpg') },
  //   { name: 'starships_8', src: require('../assets/starships/8.jpg') },
  { name: 'starships_9', src: require('../assets/starships/9.jpg') },
  { name: 'starships_10', src: require('../assets/starships/10.jpg') },
  { name: 'starships_11', src: require('../assets/starships/11.jpg') },
  { name: 'starships_12', src: require('../assets/starships/12.jpg') },
  { name: 'starships_13', src: require('../assets/starships/13.jpg') },
  //   { name: 'starships_14', src: require('../assets/starships/14.jpg') },
  { name: 'starships_15', src: require('../assets/starships/15.jpg') },
  //   { name: 'starships_16', src: require('../assets/starships/16.jpg') },
  //   { name: 'starships_17', src: require('../assets/starships/17.jpg') }, // Rebel transport
  //   { name: 'starships_18', src: require('../assets/starships/18.jpg') },
  //   { name: 'starships_19', src: require('../assets/starships/19.jpg') },
  //   { name: 'starships_20', src: require('../assets/starships/20.jpg') },
  { name: 'starships_21', src: require('../assets/starships/21.jpg') },
  { name: 'starships_22', src: require('../assets/starships/22.jpg') },
  { name: 'starships_23', src: require('../assets/starships/23.jpg') },
  //   { name: 'starships_24', src: require('../assets/starships/24.jpg') },
  //   { name: 'starships_25', src: require('../assets/starships/25.jpg') },
  //   { name: 'starships_26', src: require('../assets/starships/26.jpg') },
  { name: 'starships_27', src: require('../assets/starships/27.jpg') },
  { name: 'starships_28', src: require('../assets/starships/28.jpg') },
  { name: 'starships_29', src: require('../assets/starships/29.jpg') },
  //   { name: 'starships_30', src: require('../assets/starships/30.jpg') },
  { name: 'starships_31', src: require('../assets/starships/31.jpg') },
  //   { name: 'starships_32', src: require('../assets/starships/32.jpg') }, // Droid control ship
  //   { name: 'starships_33', src: require('../assets/starships/33.jpg') },
  //   { name: 'starships_34', src: require('../assets/starships/34.jpg') },
  //   { name: 'starships_35', src: require('../assets/starships/35.jpg') },
  //   { name: 'starships_36', src: require('../assets/starships/36.jpg') },
];

const getImageByName = (key: string) => {
  const index = images.findIndex(x => x.name === key);
  return images[index].src;
};

export default getImageByName;
